apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../components/operators/cert-manager
  - ../../components/operators/kueue-operator
  - ../../components/operators/cluster-observability-operator
  - ../../components/operators/opentelemetry-product
  - ../../components/operators/leader-worker-set
  - ../../components/operators/job-set-operator
  - ../../components/operators/tempo-product
  - ../../components/operators/openshift-custom-metrics-autoscaler
