{{- $dep := .Values.dependencies.rhcl -}}
{{- $shouldInstall := include "rhoai-dependencies.shouldInstall" (dict "dependencyName" "rhcl" "dependency" $dep "dependencies" .Values.dependencies "components" .Values.components "services" .Values.services) -}}
{{- if eq $shouldInstall "true" }}
{{- if and $dep.config $dep.config.tlsEnabled }}
{{- if include "rhoai-dependencies.crdExists" (dict "crdName" "authorinos.operator.authorino.kuadrant.io" "root" $) }}
apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: {{ $dep.olm.namespace }}
  labels:
    {{- include "rhoai-dependencies.labels" . | nindent 4 }}
{{- with $dep.config.authorinoSpec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
